"""
Banned phrases for comment generation.

AI_CLICHE_PHRASES: Generic filler language that makes comments feel hollow.
BOT_INDICATOR_PHRASES: Phrases that reveal automated or AI-generated origin.
AI_PUNCTUATION: Punctuation patterns that immediately signal AI authorship.
"""

AI_CLICHE_PHRASES: tuple[str, ...] = (
    "Great post!",
    "Insightful!",
    "Very insightful",
    "Insightful post",
    "Great insights",
    "Great insight",
    "Amazing post",
    "Excellent post",
    "Wonderful post",
    "Fantastic post",
    "Brilliant post",
    "Love this post",
    "Love this!",
    "So true!",
    "Spot on!",
    "100%!",
    "Totally agree",
    "Couldn't agree more",
    "Well said",
    "Nicely put",
    "Thanks for sharing",
    "Thanks for sharing!",
    "Thank you for sharing",
    "game-changer",
    "game changer",
    "leverage",
    "synergy",
    "synergies",
    "paradigm shift",
    "thought leader",
    "thought leadership",
    "disruptive",
    "disrupting the industry",
    "cutting-edge",
    "state-of-the-art",
    "best practices",
    "circle back",
    "move the needle",
    "low-hanging fruit",
    "deep dive",
    "bandwidth",
    "pivot",
    "scalable",
    "value-add",
    "actionable insights",
    "key takeaways",
)

BOT_INDICATOR_PHRASES: tuple[str, ...] = (
    "As an AI",
    "As an AI language model",
    "I'm an AI",
    "I am an AI",
    "generated by AI",
    "AI-generated",
    "automated comment",
    "this comment was generated",
    "language model",
    "large language model",
    "LLM",
    "GPT",
    "ChatGPT",
    "Gemini",
    "Claude",
    "OpenAI",
    "Anthropic",
    "machine learning model",
)

# Punctuation that screams AI — em-dash and en-dash are the #1 tell
AI_PUNCTUATION: tuple[str, ...] = (
    "\u2014",   # em-dash  —
    "\u2013",   # en-dash  –
    " - - ",    # double hyphen spaced
)

ALL_BANNED_PHRASES: tuple[str, ...] = AI_CLICHE_PHRASES + BOT_INDICATOR_PHRASES + AI_PUNCTUATION
